# Generated by Django 3.2.4 on 2021-07-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_task_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
